### ISSUE TITLE
Supress Uni/Multi and MicroProfile Message

### ISSUE THREAD

**Issue by mischwarz** [quarkiverse/quarkus-asyncapi#140]
When using the AsyncApiAnnotationScanner with return/parameter type of Uni/Multi or Microprofile Message, then the parameterized type of the payload is not as expected. I would expect to suppress the type Uni/Multi and MP-Message

For example for this Signature:

```
import org.eclipse.microprofile.reactive.messaging.Message;

@Incoming("incoming-channel-part")
@Outgoing("outgoing-channel-part")
public Uni<Message<Part>> sendMessageTyped(Message<Part>) {
    //Do nothing
    return null;
}
```

this will be generated in asyncapi.yaml

```
message:
        payload:
          type: "object"
        contentType: "application/json"
        name: "io.smallrye.mutiny.Uni"
```

instead of expected

```
      message:
        payload:
          $ref: "#/components/schemas/Part"
        contentType: "application/json"
        name: "o.quarkiverse.asyncapi.annotation.scanner.Part"
```
