### ISSUE TITLE
@JsonProperty is ignored when generated from scanner

### ISSUE THREAD

**Issue by jogerj** [quarkiverse/quarkus-asyncapi#157]
```java
public class Foo {
    
    @JsonProperty("baz")
    String bar;
    
    public Foo(String bar) {
        this.bar = bar;
    }
}
```

Suppose I have a DTO `Foo`, the asyncapi.yaml generated by the scanner defines `Foo` as follows:

```yaml
Foo:
  type: "object"
  properties:
    bar:
      type: "string"
```

Which is incorrect since `bar` should be (de)serialized into `baz` 

Version: 0.2.2

**Comment by jogerj** [comment]
```java
public class Foo {
    @JsonValue
    public String bar;

    public Foo(String bar) { this.bar = bar; }
}
```

The issue seems to also affect other Jackson annotations such as `JsonValue` are used, in this case the definition of `Foo` generated is:
```yaml
# Expected
Foo:
  type: "string"
# Actual
Foo:
  type: "object"
  properties:
    bar:
      type: "string"
```
